### PR TITLE
Update to 2023.12

### PR DESCRIPTION
**Pull request by alemuntoni**

### CODE REVIEW

**Comment by alemuntoni** [comment]
@kevinsmia1939 now external libraries are ok. The only missing library, that is now required to build filter embree, is TBB, that must be installed in the system. Do you know how to install it correctly (in the same way that is done for cgal, boost...)?

For the cmake problem, I'll fix it on the meshlab repo and when the build wll success I'll create a new tag (probably `MeshLab-2023.12.1` or `MeshLab-2023.12.post1`).

**Comment by kevinsmia1939** [comment]
Just add this 

```
  - name: TBB
    buildsystem: cmake-ninja
    config-opts:
      - -DTBB_TEST=OFF
      - -DTBB_EXAMPLES=OFF
    builddir: true
    sources:
      - type: archive
        url: https://github.com/oneapi-src/oneTBB/archive/refs/tags/v2021.11.0.tar.gz
        sha256: 782ce0cab62df9ea125cdea253a50534862b563f1d85d4cda7ad4e77550ac363
        x-checker-data:
          type: anitya
          project-id: 8217
          stable-only: true
          url-template: https://github.com/oneapi-src/oneTBB/archive/refs/tags/v$version.tar.gz
```

**Comment by alemuntoni** [comment]
@kevinsmia1939 it was a very silly error, I just forgot that last year I did changed the directory of the main CMakeLists.txt, which is now in the root of the repo and not anymore in the `src` folder... I'm sorry I wasted your time for this :(

Anyway, now the flatpak looks fine, all the plugins have been built and from my side it can be merged.
Let me know if any other change is required!

**Comment by kevinsmia1939** [comment]
> @kevinsmia1939 it was a very silly error, I just forgot that last year I did changed the directory of the main CMakeLists.txt, which is now in the root of the repo and not anymore in the `src` folder... I'm sorry I wasted your time for this :(
> 
> Anyway, now the flatpak looks fine, all the plugins have been built and from my side it can be merged. Let me know if any other change is required!

No worries at all, I'm happy to maintain this. I think this looks fine. I will merge it.

**Pull request merged**
