### PR TITLE
Update to Meshlab 2023.12

### PR DESCRIPTION
**Pull request by kevinsmia1939**

### CODE REVIEW

**Comment by alemuntoni** [comment]
You should not need to download vcg, nexus (and also other libraries too) separately.
vcg is a submodule and nexus (along the other libraries) is downloaded automatically by cmake when is needed.

I think that we should investigate on why cmake was complaining about the "LIBRARY DESTINATION" missing on targets.

**Comment by kevinsmia1939** [comment]
> You should not need to download vcg, nexus (and also other libraries too) separately. vcg is a submodule and nexus (along the other libraries) is downloaded automatically by cmake when is needed.
> 
> I think that we should investigate on why cmake was complaining about the "LIBRARY DESTINATION" missing on targets.

Hi, there is no network connection during build time inside Flatpak build system. So it will need to be include.

**Comment by alemuntoni** [comment]
> > You should not need to download vcg, nexus (and also other libraries too) separately. vcg is a submodule and nexus (along the other libraries) is downloaded automatically by cmake when is needed.
> > I think that we should investigate on why cmake was complaining about the "LIBRARY DESTINATION" missing on targets.
> 
> Hi, there is no network connection during build time inside Flatpak build system. So it will need to be include.

Argh!!! I see! Therefore there are also other libraries that need to be downloaded first... 
Ok, I'll try to manually download what is needed!

**Comment by alemuntoni** [comment]
> there is no network connection during build time inside Flatpak build system

2022.02 version worked because we used to boundle all the external libraries inside the repo. We changed that in order to better keep track of the required external libraries...

So, I think that the best way to proceed is the following:

- download the MeshLab sources at the tag 2023.12
- download the following external libraries sources and place them in `src/external/downloads/`, as made by cmake for example [here](https://github.com/cnr-isti-vclab/meshlab/blob/main/src/external/libigl.cmake):
  - embree
  - levmar
  - libigl
  - muparser
  - nexus (and corto)
  - newuoa
  - openctm
  - qhull
  - ssynth
  - tinygltf
  - u3d
  - xcerces
  - e57
- start the build of MeshLab; cmake will ignore all the sources that already finds in `src/external/downloads/`

@kevinsmia1939 I just don't know enough the flatpak syntax to do that, but if you could prepare a skeleton for these step, then I can add all the required additional libraries.

**Comment by alemuntoni** [comment]
I hope that this could be useful... I made a separate repo containing the required external libraries [here](https://github.com/alemuntoni/meshlab-external-libraries). 

Just downloading the content of the repo inside the src/external directory should work!

**Pull request closed without merging**
